//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18047
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyoeiSystem.Framework.Core.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="M04_DRV_Member", Namespace="http://schemas.datacontract.org/2004/07/KyoeiSystem.Data")]
    [System.SerializableAttribute()]
    public partial class M04_DRV_Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string かな読みField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> デジタコCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 乗務員IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 乗務員名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 事業者コードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> 住居の種類Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 住所１_１Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 住所１_２Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 住所２_１Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 住所２_２Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 作成番号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 健康保険加入日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 健康保険番号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 備考Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 免許種類9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 免許証取得年月日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 免許証条件Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 免許証番号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 入社日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 写真Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 労災保険加入日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 労災保険番号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 厚生年金加入日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 厚生年金番号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 受診状況Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 変更日付1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 変更日付2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 変更日付3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 変更理由1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 変更理由2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 変更理由3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 変更職種1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 変更職種2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 変更職種3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族氏名1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族氏名2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族氏名3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族氏名4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族氏名5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族氏名6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 家族生年月日1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 家族生年月日2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 家族生年月日3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 家族生年月日4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 家族生年月日5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 家族生年月日6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族続柄1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族続柄2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族続柄3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族続柄4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族続柄5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族続柄6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家族連絡Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 就労区分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 履歴事業所1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 履歴事業所2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴定員1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴定員2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 履歴年月日1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 履歴年月日2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 履歴年月日3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 履歴年月日4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 履歴年月日5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴種類1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴種類2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 履歴積載量1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 履歴積載量2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴経験年1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴経験年2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴経験月1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 履歴経験月2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 性別区分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 携帯電話Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 撮影年Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 撮影月Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 更新日時Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終学歴1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終学歴2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終学歴3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終学歴4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終学歴5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 有効年月日8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 有効番号8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 歩合率Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 歩合計算区分IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 水揚連動区分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 生年月日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 登録日時Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 経費割当車輌IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 職種Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 職種分類Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 職種分類区分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 自傭区分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 自社部門IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 血液型Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 資格名称1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 資格名称2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 資格名称3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 資格名称4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 資格年月日1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 資格年月日2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 資格年月日3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 資格年月日4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 賞罰内容1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 賞罰内容2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 賞罰内容3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 賞罰内容4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 賞罰内容5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 賞罰内容6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 賞罰年月日1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 賞罰年月日2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 賞罰年月日3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 賞罰年月日4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 賞罰年月日5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 賞罰年月日6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 退職日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 退職理由Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> 通勤分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> 通勤時間Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 運転免許更新日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 運転免許有効日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 選任年月日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 郵便番号１Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 郵便番号２Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 雇入日付Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> 雇用保険加入日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 雇用保険番号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 電話番号１Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 電話番号２Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string かな読み {
            get {
                return this.かな読みField;
            }
            set {
                if ((object.ReferenceEquals(this.かな読みField, value) != true)) {
                    this.かな読みField = value;
                    this.RaisePropertyChanged("かな読み");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> デジタコCD {
            get {
                return this.デジタコCDField;
            }
            set {
                if ((this.デジタコCDField.Equals(value) != true)) {
                    this.デジタコCDField = value;
                    this.RaisePropertyChanged("デジタコCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 乗務員ID {
            get {
                return this.乗務員IDField;
            }
            set {
                if ((this.乗務員IDField.Equals(value) != true)) {
                    this.乗務員IDField = value;
                    this.RaisePropertyChanged("乗務員ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 乗務員名 {
            get {
                return this.乗務員名Field;
            }
            set {
                if ((object.ReferenceEquals(this.乗務員名Field, value) != true)) {
                    this.乗務員名Field = value;
                    this.RaisePropertyChanged("乗務員名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 事業者コード {
            get {
                return this.事業者コードField;
            }
            set {
                if ((this.事業者コードField.Equals(value) != true)) {
                    this.事業者コードField = value;
                    this.RaisePropertyChanged("事業者コード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> 住居の種類 {
            get {
                return this.住居の種類Field;
            }
            set {
                if ((this.住居の種類Field.Equals(value) != true)) {
                    this.住居の種類Field = value;
                    this.RaisePropertyChanged("住居の種類");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 住所１_１ {
            get {
                return this.住所１_１Field;
            }
            set {
                if ((object.ReferenceEquals(this.住所１_１Field, value) != true)) {
                    this.住所１_１Field = value;
                    this.RaisePropertyChanged("住所１_１");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 住所１_２ {
            get {
                return this.住所１_２Field;
            }
            set {
                if ((object.ReferenceEquals(this.住所１_２Field, value) != true)) {
                    this.住所１_２Field = value;
                    this.RaisePropertyChanged("住所１_２");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 住所２_１ {
            get {
                return this.住所２_１Field;
            }
            set {
                if ((object.ReferenceEquals(this.住所２_１Field, value) != true)) {
                    this.住所２_１Field = value;
                    this.RaisePropertyChanged("住所２_１");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 住所２_２ {
            get {
                return this.住所２_２Field;
            }
            set {
                if ((object.ReferenceEquals(this.住所２_２Field, value) != true)) {
                    this.住所２_２Field = value;
                    this.RaisePropertyChanged("住所２_２");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 作成番号 {
            get {
                return this.作成番号Field;
            }
            set {
                if ((this.作成番号Field.Equals(value) != true)) {
                    this.作成番号Field = value;
                    this.RaisePropertyChanged("作成番号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 健康保険加入日 {
            get {
                return this.健康保険加入日Field;
            }
            set {
                if ((this.健康保険加入日Field.Equals(value) != true)) {
                    this.健康保険加入日Field = value;
                    this.RaisePropertyChanged("健康保険加入日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 健康保険番号 {
            get {
                return this.健康保険番号Field;
            }
            set {
                if ((object.ReferenceEquals(this.健康保険番号Field, value) != true)) {
                    this.健康保険番号Field = value;
                    this.RaisePropertyChanged("健康保険番号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 備考 {
            get {
                return this.備考Field;
            }
            set {
                if ((object.ReferenceEquals(this.備考Field, value) != true)) {
                    this.備考Field = value;
                    this.RaisePropertyChanged("備考");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類1 {
            get {
                return this.免許種類1Field;
            }
            set {
                if ((this.免許種類1Field.Equals(value) != true)) {
                    this.免許種類1Field = value;
                    this.RaisePropertyChanged("免許種類1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類10 {
            get {
                return this.免許種類10Field;
            }
            set {
                if ((this.免許種類10Field.Equals(value) != true)) {
                    this.免許種類10Field = value;
                    this.RaisePropertyChanged("免許種類10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類2 {
            get {
                return this.免許種類2Field;
            }
            set {
                if ((this.免許種類2Field.Equals(value) != true)) {
                    this.免許種類2Field = value;
                    this.RaisePropertyChanged("免許種類2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類3 {
            get {
                return this.免許種類3Field;
            }
            set {
                if ((this.免許種類3Field.Equals(value) != true)) {
                    this.免許種類3Field = value;
                    this.RaisePropertyChanged("免許種類3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類4 {
            get {
                return this.免許種類4Field;
            }
            set {
                if ((this.免許種類4Field.Equals(value) != true)) {
                    this.免許種類4Field = value;
                    this.RaisePropertyChanged("免許種類4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類5 {
            get {
                return this.免許種類5Field;
            }
            set {
                if ((this.免許種類5Field.Equals(value) != true)) {
                    this.免許種類5Field = value;
                    this.RaisePropertyChanged("免許種類5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類6 {
            get {
                return this.免許種類6Field;
            }
            set {
                if ((this.免許種類6Field.Equals(value) != true)) {
                    this.免許種類6Field = value;
                    this.RaisePropertyChanged("免許種類6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類7 {
            get {
                return this.免許種類7Field;
            }
            set {
                if ((this.免許種類7Field.Equals(value) != true)) {
                    this.免許種類7Field = value;
                    this.RaisePropertyChanged("免許種類7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類8 {
            get {
                return this.免許種類8Field;
            }
            set {
                if ((this.免許種類8Field.Equals(value) != true)) {
                    this.免許種類8Field = value;
                    this.RaisePropertyChanged("免許種類8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 免許種類9 {
            get {
                return this.免許種類9Field;
            }
            set {
                if ((this.免許種類9Field.Equals(value) != true)) {
                    this.免許種類9Field = value;
                    this.RaisePropertyChanged("免許種類9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 免許証取得年月日 {
            get {
                return this.免許証取得年月日Field;
            }
            set {
                if ((this.免許証取得年月日Field.Equals(value) != true)) {
                    this.免許証取得年月日Field = value;
                    this.RaisePropertyChanged("免許証取得年月日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 免許証条件 {
            get {
                return this.免許証条件Field;
            }
            set {
                if ((object.ReferenceEquals(this.免許証条件Field, value) != true)) {
                    this.免許証条件Field = value;
                    this.RaisePropertyChanged("免許証条件");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 免許証番号 {
            get {
                return this.免許証番号Field;
            }
            set {
                if ((object.ReferenceEquals(this.免許証番号Field, value) != true)) {
                    this.免許証番号Field = value;
                    this.RaisePropertyChanged("免許証番号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 入社日 {
            get {
                return this.入社日Field;
            }
            set {
                if ((this.入社日Field.Equals(value) != true)) {
                    this.入社日Field = value;
                    this.RaisePropertyChanged("入社日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 写真 {
            get {
                return this.写真Field;
            }
            set {
                if ((object.ReferenceEquals(this.写真Field, value) != true)) {
                    this.写真Field = value;
                    this.RaisePropertyChanged("写真");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 労災保険加入日 {
            get {
                return this.労災保険加入日Field;
            }
            set {
                if ((this.労災保険加入日Field.Equals(value) != true)) {
                    this.労災保険加入日Field = value;
                    this.RaisePropertyChanged("労災保険加入日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 労災保険番号 {
            get {
                return this.労災保険番号Field;
            }
            set {
                if ((object.ReferenceEquals(this.労災保険番号Field, value) != true)) {
                    this.労災保険番号Field = value;
                    this.RaisePropertyChanged("労災保険番号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 厚生年金加入日 {
            get {
                return this.厚生年金加入日Field;
            }
            set {
                if ((this.厚生年金加入日Field.Equals(value) != true)) {
                    this.厚生年金加入日Field = value;
                    this.RaisePropertyChanged("厚生年金加入日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 厚生年金番号 {
            get {
                return this.厚生年金番号Field;
            }
            set {
                if ((object.ReferenceEquals(this.厚生年金番号Field, value) != true)) {
                    this.厚生年金番号Field = value;
                    this.RaisePropertyChanged("厚生年金番号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 受診状況 {
            get {
                return this.受診状況Field;
            }
            set {
                if ((object.ReferenceEquals(this.受診状況Field, value) != true)) {
                    this.受診状況Field = value;
                    this.RaisePropertyChanged("受診状況");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 変更日付1 {
            get {
                return this.変更日付1Field;
            }
            set {
                if ((this.変更日付1Field.Equals(value) != true)) {
                    this.変更日付1Field = value;
                    this.RaisePropertyChanged("変更日付1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 変更日付2 {
            get {
                return this.変更日付2Field;
            }
            set {
                if ((this.変更日付2Field.Equals(value) != true)) {
                    this.変更日付2Field = value;
                    this.RaisePropertyChanged("変更日付2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 変更日付3 {
            get {
                return this.変更日付3Field;
            }
            set {
                if ((this.変更日付3Field.Equals(value) != true)) {
                    this.変更日付3Field = value;
                    this.RaisePropertyChanged("変更日付3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 変更理由1 {
            get {
                return this.変更理由1Field;
            }
            set {
                if ((object.ReferenceEquals(this.変更理由1Field, value) != true)) {
                    this.変更理由1Field = value;
                    this.RaisePropertyChanged("変更理由1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 変更理由2 {
            get {
                return this.変更理由2Field;
            }
            set {
                if ((object.ReferenceEquals(this.変更理由2Field, value) != true)) {
                    this.変更理由2Field = value;
                    this.RaisePropertyChanged("変更理由2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 変更理由3 {
            get {
                return this.変更理由3Field;
            }
            set {
                if ((object.ReferenceEquals(this.変更理由3Field, value) != true)) {
                    this.変更理由3Field = value;
                    this.RaisePropertyChanged("変更理由3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 変更職種1 {
            get {
                return this.変更職種1Field;
            }
            set {
                if ((object.ReferenceEquals(this.変更職種1Field, value) != true)) {
                    this.変更職種1Field = value;
                    this.RaisePropertyChanged("変更職種1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 変更職種2 {
            get {
                return this.変更職種2Field;
            }
            set {
                if ((object.ReferenceEquals(this.変更職種2Field, value) != true)) {
                    this.変更職種2Field = value;
                    this.RaisePropertyChanged("変更職種2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 変更職種3 {
            get {
                return this.変更職種3Field;
            }
            set {
                if ((object.ReferenceEquals(this.変更職種3Field, value) != true)) {
                    this.変更職種3Field = value;
                    this.RaisePropertyChanged("変更職種3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族氏名1 {
            get {
                return this.家族氏名1Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族氏名1Field, value) != true)) {
                    this.家族氏名1Field = value;
                    this.RaisePropertyChanged("家族氏名1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族氏名2 {
            get {
                return this.家族氏名2Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族氏名2Field, value) != true)) {
                    this.家族氏名2Field = value;
                    this.RaisePropertyChanged("家族氏名2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族氏名3 {
            get {
                return this.家族氏名3Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族氏名3Field, value) != true)) {
                    this.家族氏名3Field = value;
                    this.RaisePropertyChanged("家族氏名3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族氏名4 {
            get {
                return this.家族氏名4Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族氏名4Field, value) != true)) {
                    this.家族氏名4Field = value;
                    this.RaisePropertyChanged("家族氏名4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族氏名5 {
            get {
                return this.家族氏名5Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族氏名5Field, value) != true)) {
                    this.家族氏名5Field = value;
                    this.RaisePropertyChanged("家族氏名5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族氏名6 {
            get {
                return this.家族氏名6Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族氏名6Field, value) != true)) {
                    this.家族氏名6Field = value;
                    this.RaisePropertyChanged("家族氏名6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 家族生年月日1 {
            get {
                return this.家族生年月日1Field;
            }
            set {
                if ((this.家族生年月日1Field.Equals(value) != true)) {
                    this.家族生年月日1Field = value;
                    this.RaisePropertyChanged("家族生年月日1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 家族生年月日2 {
            get {
                return this.家族生年月日2Field;
            }
            set {
                if ((this.家族生年月日2Field.Equals(value) != true)) {
                    this.家族生年月日2Field = value;
                    this.RaisePropertyChanged("家族生年月日2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 家族生年月日3 {
            get {
                return this.家族生年月日3Field;
            }
            set {
                if ((this.家族生年月日3Field.Equals(value) != true)) {
                    this.家族生年月日3Field = value;
                    this.RaisePropertyChanged("家族生年月日3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 家族生年月日4 {
            get {
                return this.家族生年月日4Field;
            }
            set {
                if ((this.家族生年月日4Field.Equals(value) != true)) {
                    this.家族生年月日4Field = value;
                    this.RaisePropertyChanged("家族生年月日4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 家族生年月日5 {
            get {
                return this.家族生年月日5Field;
            }
            set {
                if ((this.家族生年月日5Field.Equals(value) != true)) {
                    this.家族生年月日5Field = value;
                    this.RaisePropertyChanged("家族生年月日5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 家族生年月日6 {
            get {
                return this.家族生年月日6Field;
            }
            set {
                if ((this.家族生年月日6Field.Equals(value) != true)) {
                    this.家族生年月日6Field = value;
                    this.RaisePropertyChanged("家族生年月日6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族続柄1 {
            get {
                return this.家族続柄1Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族続柄1Field, value) != true)) {
                    this.家族続柄1Field = value;
                    this.RaisePropertyChanged("家族続柄1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族続柄2 {
            get {
                return this.家族続柄2Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族続柄2Field, value) != true)) {
                    this.家族続柄2Field = value;
                    this.RaisePropertyChanged("家族続柄2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族続柄3 {
            get {
                return this.家族続柄3Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族続柄3Field, value) != true)) {
                    this.家族続柄3Field = value;
                    this.RaisePropertyChanged("家族続柄3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族続柄4 {
            get {
                return this.家族続柄4Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族続柄4Field, value) != true)) {
                    this.家族続柄4Field = value;
                    this.RaisePropertyChanged("家族続柄4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族続柄5 {
            get {
                return this.家族続柄5Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族続柄5Field, value) != true)) {
                    this.家族続柄5Field = value;
                    this.RaisePropertyChanged("家族続柄5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族続柄6 {
            get {
                return this.家族続柄6Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族続柄6Field, value) != true)) {
                    this.家族続柄6Field = value;
                    this.RaisePropertyChanged("家族続柄6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家族連絡 {
            get {
                return this.家族連絡Field;
            }
            set {
                if ((object.ReferenceEquals(this.家族連絡Field, value) != true)) {
                    this.家族連絡Field = value;
                    this.RaisePropertyChanged("家族連絡");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 就労区分 {
            get {
                return this.就労区分Field;
            }
            set {
                if ((this.就労区分Field.Equals(value) != true)) {
                    this.就労区分Field = value;
                    this.RaisePropertyChanged("就労区分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 履歴事業所1 {
            get {
                return this.履歴事業所1Field;
            }
            set {
                if ((object.ReferenceEquals(this.履歴事業所1Field, value) != true)) {
                    this.履歴事業所1Field = value;
                    this.RaisePropertyChanged("履歴事業所1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 履歴事業所2 {
            get {
                return this.履歴事業所2Field;
            }
            set {
                if ((object.ReferenceEquals(this.履歴事業所2Field, value) != true)) {
                    this.履歴事業所2Field = value;
                    this.RaisePropertyChanged("履歴事業所2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴定員1 {
            get {
                return this.履歴定員1Field;
            }
            set {
                if ((this.履歴定員1Field.Equals(value) != true)) {
                    this.履歴定員1Field = value;
                    this.RaisePropertyChanged("履歴定員1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴定員2 {
            get {
                return this.履歴定員2Field;
            }
            set {
                if ((this.履歴定員2Field.Equals(value) != true)) {
                    this.履歴定員2Field = value;
                    this.RaisePropertyChanged("履歴定員2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 履歴年月日1 {
            get {
                return this.履歴年月日1Field;
            }
            set {
                if ((this.履歴年月日1Field.Equals(value) != true)) {
                    this.履歴年月日1Field = value;
                    this.RaisePropertyChanged("履歴年月日1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 履歴年月日2 {
            get {
                return this.履歴年月日2Field;
            }
            set {
                if ((this.履歴年月日2Field.Equals(value) != true)) {
                    this.履歴年月日2Field = value;
                    this.RaisePropertyChanged("履歴年月日2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 履歴年月日3 {
            get {
                return this.履歴年月日3Field;
            }
            set {
                if ((this.履歴年月日3Field.Equals(value) != true)) {
                    this.履歴年月日3Field = value;
                    this.RaisePropertyChanged("履歴年月日3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 履歴年月日4 {
            get {
                return this.履歴年月日4Field;
            }
            set {
                if ((this.履歴年月日4Field.Equals(value) != true)) {
                    this.履歴年月日4Field = value;
                    this.RaisePropertyChanged("履歴年月日4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 履歴年月日5 {
            get {
                return this.履歴年月日5Field;
            }
            set {
                if ((this.履歴年月日5Field.Equals(value) != true)) {
                    this.履歴年月日5Field = value;
                    this.RaisePropertyChanged("履歴年月日5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴種類1 {
            get {
                return this.履歴種類1Field;
            }
            set {
                if ((this.履歴種類1Field.Equals(value) != true)) {
                    this.履歴種類1Field = value;
                    this.RaisePropertyChanged("履歴種類1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴種類2 {
            get {
                return this.履歴種類2Field;
            }
            set {
                if ((this.履歴種類2Field.Equals(value) != true)) {
                    this.履歴種類2Field = value;
                    this.RaisePropertyChanged("履歴種類2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 履歴積載量1 {
            get {
                return this.履歴積載量1Field;
            }
            set {
                if ((this.履歴積載量1Field.Equals(value) != true)) {
                    this.履歴積載量1Field = value;
                    this.RaisePropertyChanged("履歴積載量1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 履歴積載量2 {
            get {
                return this.履歴積載量2Field;
            }
            set {
                if ((this.履歴積載量2Field.Equals(value) != true)) {
                    this.履歴積載量2Field = value;
                    this.RaisePropertyChanged("履歴積載量2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴経験年1 {
            get {
                return this.履歴経験年1Field;
            }
            set {
                if ((this.履歴経験年1Field.Equals(value) != true)) {
                    this.履歴経験年1Field = value;
                    this.RaisePropertyChanged("履歴経験年1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴経験年2 {
            get {
                return this.履歴経験年2Field;
            }
            set {
                if ((this.履歴経験年2Field.Equals(value) != true)) {
                    this.履歴経験年2Field = value;
                    this.RaisePropertyChanged("履歴経験年2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴経験月1 {
            get {
                return this.履歴経験月1Field;
            }
            set {
                if ((this.履歴経験月1Field.Equals(value) != true)) {
                    this.履歴経験月1Field = value;
                    this.RaisePropertyChanged("履歴経験月1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 履歴経験月2 {
            get {
                return this.履歴経験月2Field;
            }
            set {
                if ((this.履歴経験月2Field.Equals(value) != true)) {
                    this.履歴経験月2Field = value;
                    this.RaisePropertyChanged("履歴経験月2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 性別区分 {
            get {
                return this.性別区分Field;
            }
            set {
                if ((this.性別区分Field.Equals(value) != true)) {
                    this.性別区分Field = value;
                    this.RaisePropertyChanged("性別区分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 携帯電話 {
            get {
                return this.携帯電話Field;
            }
            set {
                if ((object.ReferenceEquals(this.携帯電話Field, value) != true)) {
                    this.携帯電話Field = value;
                    this.RaisePropertyChanged("携帯電話");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 撮影年 {
            get {
                return this.撮影年Field;
            }
            set {
                if ((this.撮影年Field.Equals(value) != true)) {
                    this.撮影年Field = value;
                    this.RaisePropertyChanged("撮影年");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 撮影月 {
            get {
                return this.撮影月Field;
            }
            set {
                if ((this.撮影月Field.Equals(value) != true)) {
                    this.撮影月Field = value;
                    this.RaisePropertyChanged("撮影月");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 更新日時 {
            get {
                return this.更新日時Field;
            }
            set {
                if ((this.更新日時Field.Equals(value) != true)) {
                    this.更新日時Field = value;
                    this.RaisePropertyChanged("更新日時");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終学歴1 {
            get {
                return this.最終学歴1Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終学歴1Field, value) != true)) {
                    this.最終学歴1Field = value;
                    this.RaisePropertyChanged("最終学歴1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終学歴2 {
            get {
                return this.最終学歴2Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終学歴2Field, value) != true)) {
                    this.最終学歴2Field = value;
                    this.RaisePropertyChanged("最終学歴2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終学歴3 {
            get {
                return this.最終学歴3Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終学歴3Field, value) != true)) {
                    this.最終学歴3Field = value;
                    this.RaisePropertyChanged("最終学歴3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終学歴4 {
            get {
                return this.最終学歴4Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終学歴4Field, value) != true)) {
                    this.最終学歴4Field = value;
                    this.RaisePropertyChanged("最終学歴4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終学歴5 {
            get {
                return this.最終学歴5Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終学歴5Field, value) != true)) {
                    this.最終学歴5Field = value;
                    this.RaisePropertyChanged("最終学歴5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日1 {
            get {
                return this.有効年月日1Field;
            }
            set {
                if ((this.有効年月日1Field.Equals(value) != true)) {
                    this.有効年月日1Field = value;
                    this.RaisePropertyChanged("有効年月日1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日2 {
            get {
                return this.有効年月日2Field;
            }
            set {
                if ((this.有効年月日2Field.Equals(value) != true)) {
                    this.有効年月日2Field = value;
                    this.RaisePropertyChanged("有効年月日2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日3 {
            get {
                return this.有効年月日3Field;
            }
            set {
                if ((this.有効年月日3Field.Equals(value) != true)) {
                    this.有効年月日3Field = value;
                    this.RaisePropertyChanged("有効年月日3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日4 {
            get {
                return this.有効年月日4Field;
            }
            set {
                if ((this.有効年月日4Field.Equals(value) != true)) {
                    this.有効年月日4Field = value;
                    this.RaisePropertyChanged("有効年月日4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日5 {
            get {
                return this.有効年月日5Field;
            }
            set {
                if ((this.有効年月日5Field.Equals(value) != true)) {
                    this.有効年月日5Field = value;
                    this.RaisePropertyChanged("有効年月日5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日6 {
            get {
                return this.有効年月日6Field;
            }
            set {
                if ((this.有効年月日6Field.Equals(value) != true)) {
                    this.有効年月日6Field = value;
                    this.RaisePropertyChanged("有効年月日6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日7 {
            get {
                return this.有効年月日7Field;
            }
            set {
                if ((this.有効年月日7Field.Equals(value) != true)) {
                    this.有効年月日7Field = value;
                    this.RaisePropertyChanged("有効年月日7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 有効年月日8 {
            get {
                return this.有効年月日8Field;
            }
            set {
                if ((this.有効年月日8Field.Equals(value) != true)) {
                    this.有効年月日8Field = value;
                    this.RaisePropertyChanged("有効年月日8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号1 {
            get {
                return this.有効番号1Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号1Field, value) != true)) {
                    this.有効番号1Field = value;
                    this.RaisePropertyChanged("有効番号1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号2 {
            get {
                return this.有効番号2Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号2Field, value) != true)) {
                    this.有効番号2Field = value;
                    this.RaisePropertyChanged("有効番号2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号3 {
            get {
                return this.有効番号3Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号3Field, value) != true)) {
                    this.有効番号3Field = value;
                    this.RaisePropertyChanged("有効番号3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号4 {
            get {
                return this.有効番号4Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号4Field, value) != true)) {
                    this.有効番号4Field = value;
                    this.RaisePropertyChanged("有効番号4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号5 {
            get {
                return this.有効番号5Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号5Field, value) != true)) {
                    this.有効番号5Field = value;
                    this.RaisePropertyChanged("有効番号5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号6 {
            get {
                return this.有効番号6Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号6Field, value) != true)) {
                    this.有効番号6Field = value;
                    this.RaisePropertyChanged("有効番号6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号7 {
            get {
                return this.有効番号7Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号7Field, value) != true)) {
                    this.有効番号7Field = value;
                    this.RaisePropertyChanged("有効番号7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 有効番号8 {
            get {
                return this.有効番号8Field;
            }
            set {
                if ((object.ReferenceEquals(this.有効番号8Field, value) != true)) {
                    this.有効番号8Field = value;
                    this.RaisePropertyChanged("有効番号8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 歩合率 {
            get {
                return this.歩合率Field;
            }
            set {
                if ((this.歩合率Field.Equals(value) != true)) {
                    this.歩合率Field = value;
                    this.RaisePropertyChanged("歩合率");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 歩合計算区分ID {
            get {
                return this.歩合計算区分IDField;
            }
            set {
                if ((this.歩合計算区分IDField.Equals(value) != true)) {
                    this.歩合計算区分IDField = value;
                    this.RaisePropertyChanged("歩合計算区分ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 水揚連動区分 {
            get {
                return this.水揚連動区分Field;
            }
            set {
                if ((this.水揚連動区分Field.Equals(value) != true)) {
                    this.水揚連動区分Field = value;
                    this.RaisePropertyChanged("水揚連動区分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 生年月日 {
            get {
                return this.生年月日Field;
            }
            set {
                if ((this.生年月日Field.Equals(value) != true)) {
                    this.生年月日Field = value;
                    this.RaisePropertyChanged("生年月日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 登録日時 {
            get {
                return this.登録日時Field;
            }
            set {
                if ((this.登録日時Field.Equals(value) != true)) {
                    this.登録日時Field = value;
                    this.RaisePropertyChanged("登録日時");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 経費割当車輌ID {
            get {
                return this.経費割当車輌IDField;
            }
            set {
                if ((this.経費割当車輌IDField.Equals(value) != true)) {
                    this.経費割当車輌IDField = value;
                    this.RaisePropertyChanged("経費割当車輌ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 職種 {
            get {
                return this.職種Field;
            }
            set {
                if ((object.ReferenceEquals(this.職種Field, value) != true)) {
                    this.職種Field = value;
                    this.RaisePropertyChanged("職種");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 職種分類 {
            get {
                return this.職種分類Field;
            }
            set {
                if ((object.ReferenceEquals(this.職種分類Field, value) != true)) {
                    this.職種分類Field = value;
                    this.RaisePropertyChanged("職種分類");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 職種分類区分 {
            get {
                return this.職種分類区分Field;
            }
            set {
                if ((this.職種分類区分Field.Equals(value) != true)) {
                    this.職種分類区分Field = value;
                    this.RaisePropertyChanged("職種分類区分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 自傭区分 {
            get {
                return this.自傭区分Field;
            }
            set {
                if ((this.自傭区分Field.Equals(value) != true)) {
                    this.自傭区分Field = value;
                    this.RaisePropertyChanged("自傭区分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 自社部門ID {
            get {
                return this.自社部門IDField;
            }
            set {
                if ((this.自社部門IDField.Equals(value) != true)) {
                    this.自社部門IDField = value;
                    this.RaisePropertyChanged("自社部門ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 血液型 {
            get {
                return this.血液型Field;
            }
            set {
                if ((this.血液型Field.Equals(value) != true)) {
                    this.血液型Field = value;
                    this.RaisePropertyChanged("血液型");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 資格名称1 {
            get {
                return this.資格名称1Field;
            }
            set {
                if ((object.ReferenceEquals(this.資格名称1Field, value) != true)) {
                    this.資格名称1Field = value;
                    this.RaisePropertyChanged("資格名称1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 資格名称2 {
            get {
                return this.資格名称2Field;
            }
            set {
                if ((object.ReferenceEquals(this.資格名称2Field, value) != true)) {
                    this.資格名称2Field = value;
                    this.RaisePropertyChanged("資格名称2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 資格名称3 {
            get {
                return this.資格名称3Field;
            }
            set {
                if ((object.ReferenceEquals(this.資格名称3Field, value) != true)) {
                    this.資格名称3Field = value;
                    this.RaisePropertyChanged("資格名称3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 資格名称4 {
            get {
                return this.資格名称4Field;
            }
            set {
                if ((object.ReferenceEquals(this.資格名称4Field, value) != true)) {
                    this.資格名称4Field = value;
                    this.RaisePropertyChanged("資格名称4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 資格年月日1 {
            get {
                return this.資格年月日1Field;
            }
            set {
                if ((this.資格年月日1Field.Equals(value) != true)) {
                    this.資格年月日1Field = value;
                    this.RaisePropertyChanged("資格年月日1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 資格年月日2 {
            get {
                return this.資格年月日2Field;
            }
            set {
                if ((this.資格年月日2Field.Equals(value) != true)) {
                    this.資格年月日2Field = value;
                    this.RaisePropertyChanged("資格年月日2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 資格年月日3 {
            get {
                return this.資格年月日3Field;
            }
            set {
                if ((this.資格年月日3Field.Equals(value) != true)) {
                    this.資格年月日3Field = value;
                    this.RaisePropertyChanged("資格年月日3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 資格年月日4 {
            get {
                return this.資格年月日4Field;
            }
            set {
                if ((this.資格年月日4Field.Equals(value) != true)) {
                    this.資格年月日4Field = value;
                    this.RaisePropertyChanged("資格年月日4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 賞罰内容1 {
            get {
                return this.賞罰内容1Field;
            }
            set {
                if ((object.ReferenceEquals(this.賞罰内容1Field, value) != true)) {
                    this.賞罰内容1Field = value;
                    this.RaisePropertyChanged("賞罰内容1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 賞罰内容2 {
            get {
                return this.賞罰内容2Field;
            }
            set {
                if ((object.ReferenceEquals(this.賞罰内容2Field, value) != true)) {
                    this.賞罰内容2Field = value;
                    this.RaisePropertyChanged("賞罰内容2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 賞罰内容3 {
            get {
                return this.賞罰内容3Field;
            }
            set {
                if ((object.ReferenceEquals(this.賞罰内容3Field, value) != true)) {
                    this.賞罰内容3Field = value;
                    this.RaisePropertyChanged("賞罰内容3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 賞罰内容4 {
            get {
                return this.賞罰内容4Field;
            }
            set {
                if ((object.ReferenceEquals(this.賞罰内容4Field, value) != true)) {
                    this.賞罰内容4Field = value;
                    this.RaisePropertyChanged("賞罰内容4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 賞罰内容5 {
            get {
                return this.賞罰内容5Field;
            }
            set {
                if ((object.ReferenceEquals(this.賞罰内容5Field, value) != true)) {
                    this.賞罰内容5Field = value;
                    this.RaisePropertyChanged("賞罰内容5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 賞罰内容6 {
            get {
                return this.賞罰内容6Field;
            }
            set {
                if ((object.ReferenceEquals(this.賞罰内容6Field, value) != true)) {
                    this.賞罰内容6Field = value;
                    this.RaisePropertyChanged("賞罰内容6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 賞罰年月日1 {
            get {
                return this.賞罰年月日1Field;
            }
            set {
                if ((this.賞罰年月日1Field.Equals(value) != true)) {
                    this.賞罰年月日1Field = value;
                    this.RaisePropertyChanged("賞罰年月日1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 賞罰年月日2 {
            get {
                return this.賞罰年月日2Field;
            }
            set {
                if ((this.賞罰年月日2Field.Equals(value) != true)) {
                    this.賞罰年月日2Field = value;
                    this.RaisePropertyChanged("賞罰年月日2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 賞罰年月日3 {
            get {
                return this.賞罰年月日3Field;
            }
            set {
                if ((this.賞罰年月日3Field.Equals(value) != true)) {
                    this.賞罰年月日3Field = value;
                    this.RaisePropertyChanged("賞罰年月日3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 賞罰年月日4 {
            get {
                return this.賞罰年月日4Field;
            }
            set {
                if ((this.賞罰年月日4Field.Equals(value) != true)) {
                    this.賞罰年月日4Field = value;
                    this.RaisePropertyChanged("賞罰年月日4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 賞罰年月日5 {
            get {
                return this.賞罰年月日5Field;
            }
            set {
                if ((this.賞罰年月日5Field.Equals(value) != true)) {
                    this.賞罰年月日5Field = value;
                    this.RaisePropertyChanged("賞罰年月日5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 賞罰年月日6 {
            get {
                return this.賞罰年月日6Field;
            }
            set {
                if ((this.賞罰年月日6Field.Equals(value) != true)) {
                    this.賞罰年月日6Field = value;
                    this.RaisePropertyChanged("賞罰年月日6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 退職日 {
            get {
                return this.退職日Field;
            }
            set {
                if ((this.退職日Field.Equals(value) != true)) {
                    this.退職日Field = value;
                    this.RaisePropertyChanged("退職日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 退職理由 {
            get {
                return this.退職理由Field;
            }
            set {
                if ((object.ReferenceEquals(this.退職理由Field, value) != true)) {
                    this.退職理由Field = value;
                    this.RaisePropertyChanged("退職理由");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> 通勤分 {
            get {
                return this.通勤分Field;
            }
            set {
                if ((this.通勤分Field.Equals(value) != true)) {
                    this.通勤分Field = value;
                    this.RaisePropertyChanged("通勤分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> 通勤時間 {
            get {
                return this.通勤時間Field;
            }
            set {
                if ((this.通勤時間Field.Equals(value) != true)) {
                    this.通勤時間Field = value;
                    this.RaisePropertyChanged("通勤時間");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 運転免許更新日 {
            get {
                return this.運転免許更新日Field;
            }
            set {
                if ((this.運転免許更新日Field.Equals(value) != true)) {
                    this.運転免許更新日Field = value;
                    this.RaisePropertyChanged("運転免許更新日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 運転免許有効日 {
            get {
                return this.運転免許有効日Field;
            }
            set {
                if ((this.運転免許有効日Field.Equals(value) != true)) {
                    this.運転免許有効日Field = value;
                    this.RaisePropertyChanged("運転免許有効日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 選任年月日 {
            get {
                return this.選任年月日Field;
            }
            set {
                if ((this.選任年月日Field.Equals(value) != true)) {
                    this.選任年月日Field = value;
                    this.RaisePropertyChanged("選任年月日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 郵便番号１ {
            get {
                return this.郵便番号１Field;
            }
            set {
                if ((object.ReferenceEquals(this.郵便番号１Field, value) != true)) {
                    this.郵便番号１Field = value;
                    this.RaisePropertyChanged("郵便番号１");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 郵便番号２ {
            get {
                return this.郵便番号２Field;
            }
            set {
                if ((object.ReferenceEquals(this.郵便番号２Field, value) != true)) {
                    this.郵便番号２Field = value;
                    this.RaisePropertyChanged("郵便番号２");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 雇入日付 {
            get {
                return this.雇入日付Field;
            }
            set {
                if ((this.雇入日付Field.Equals(value) != true)) {
                    this.雇入日付Field = value;
                    this.RaisePropertyChanged("雇入日付");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> 雇用保険加入日 {
            get {
                return this.雇用保険加入日Field;
            }
            set {
                if ((this.雇用保険加入日Field.Equals(value) != true)) {
                    this.雇用保険加入日Field = value;
                    this.RaisePropertyChanged("雇用保険加入日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 雇用保険番号 {
            get {
                return this.雇用保険番号Field;
            }
            set {
                if ((object.ReferenceEquals(this.雇用保険番号Field, value) != true)) {
                    this.雇用保険番号Field = value;
                    this.RaisePropertyChanged("雇用保険番号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 電話番号１ {
            get {
                return this.電話番号１Field;
            }
            set {
                if ((object.ReferenceEquals(this.電話番号１Field, value) != true)) {
                    this.電話番号１Field = value;
                    this.RaisePropertyChanged("電話番号１");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 電話番号２ {
            get {
                return this.電話番号２Field;
            }
            set {
                if ((object.ReferenceEquals(this.電話番号２Field, value) != true)) {
                    this.電話番号２Field = value;
                    this.RaisePropertyChanged("電話番号２");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="M04_DRVPIC_Member", Namespace="http://schemas.datacontract.org/2004/07/KyoeiSystem.Data")]
    [System.SerializableAttribute()]
    public partial class M04_DRVPIC_Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 乗務員IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] 画像Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 乗務員ID {
            get {
                return this.乗務員IDField;
            }
            set {
                if ((this.乗務員IDField.Equals(value) != true)) {
                    this.乗務員IDField = value;
                    this.RaisePropertyChanged("乗務員ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] 画像 {
            get {
                return this.画像Field;
            }
            set {
                if ((object.ReferenceEquals(this.画像Field, value) != true)) {
                    this.画像Field = value;
                    this.RaisePropertyChanged("画像");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IM04")]
    public interface IM04 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/GetData", ReplyAction="http://tempuri.org/IM04/GetDataResponse")]
        KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member GetData(int p乗務員ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/GetData", ReplyAction="http://tempuri.org/IM04/GetDataResponse")]
        System.Threading.Tasks.Task<KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member> GetDataAsync(int p乗務員ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/GetDataGazou", ReplyAction="http://tempuri.org/IM04/GetDataGazouResponse")]
        KyoeiSystem.Framework.Core.ServiceReference1.M04_DRVPIC_Member GetDataGazou(int p乗務員ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/GetDataGazou", ReplyAction="http://tempuri.org/IM04/GetDataGazouResponse")]
        System.Threading.Tasks.Task<KyoeiSystem.Framework.Core.ServiceReference1.M04_DRVPIC_Member> GetDataGazouAsync(int p乗務員ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/RunStored", ReplyAction="http://tempuri.org/IM04/RunStoredResponse")]
        void RunStored(string pかな);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/RunStored", ReplyAction="http://tempuri.org/IM04/RunStoredResponse")]
        System.Threading.Tasks.Task RunStoredAsync(string pかな);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/Update", ReplyAction="http://tempuri.org/IM04/UpdateResponse")]
        void Update(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/Update", ReplyAction="http://tempuri.org/IM04/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/Delete", ReplyAction="http://tempuri.org/IM04/DeleteResponse")]
        void Delete(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/Delete", ReplyAction="http://tempuri.org/IM04/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/Insert", ReplyAction="http://tempuri.org/IM04/InsertResponse")]
        void Insert(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM04/Insert", ReplyAction="http://tempuri.org/IM04/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IM04Channel : KyoeiSystem.Framework.Core.ServiceReference1.IM04, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class M04Client : System.ServiceModel.ClientBase<KyoeiSystem.Framework.Core.ServiceReference1.IM04>, KyoeiSystem.Framework.Core.ServiceReference1.IM04 {
        
        public M04Client() {
        }
        
        public M04Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public M04Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public M04Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public M04Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member GetData(int p乗務員ID) {
            return base.Channel.GetData(p乗務員ID);
        }
        
        public System.Threading.Tasks.Task<KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member> GetDataAsync(int p乗務員ID) {
            return base.Channel.GetDataAsync(p乗務員ID);
        }
        
        public KyoeiSystem.Framework.Core.ServiceReference1.M04_DRVPIC_Member GetDataGazou(int p乗務員ID) {
            return base.Channel.GetDataGazou(p乗務員ID);
        }
        
        public System.Threading.Tasks.Task<KyoeiSystem.Framework.Core.ServiceReference1.M04_DRVPIC_Member> GetDataGazouAsync(int p乗務員ID) {
            return base.Channel.GetDataGazouAsync(p乗務員ID);
        }
        
        public void RunStored(string pかな) {
            base.Channel.RunStored(pかな);
        }
        
        public System.Threading.Tasks.Task RunStoredAsync(string pかな) {
            return base.Channel.RunStoredAsync(pかな);
        }
        
        public void Update(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04) {
            base.Channel.Update(m04);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04) {
            return base.Channel.UpdateAsync(m04);
        }
        
        public void Delete(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04) {
            base.Channel.Delete(m04);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04) {
            return base.Channel.DeleteAsync(m04);
        }
        
        public void Insert(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04) {
            base.Channel.Insert(m04);
        }
        
        public System.Threading.Tasks.Task InsertAsync(KyoeiSystem.Framework.Core.ServiceReference1.M04_DRV_Member m04) {
            return base.Channel.InsertAsync(m04);
        }
    }
}
